#include-once
#Region Module Constants
Global Const $GC_I_ATTRIBUTE_MIN_VALUE = 0
Global Const $GC_I_ATTRIBUTE_MAX_VALUE = 12
Global Const $GC_I_ATTRIBUTE_MAX_ATTR_POINTS = 200
Global Const $GC_I_PROFESSION_NONE = 0
Global Const $GC_I_PROFESSION_WARRIOR = 1
Global Const $GC_I_PROFESSION_RANGER = 2
Global Const $GC_I_PROFESSION_MONK = 3
Global Const $GC_I_PROFESSION_NECROMANCER = 4
Global Const $GC_I_PROFESSION_MESMER = 5
Global Const $GC_I_PROFESSION_ELEMENTALIST = 6
Global Const $GC_I_PROFESSION_ASSASSIN = 7
Global Const $GC_I_PROFESSION_RITUALIST = 8
Global Const $GC_I_PROFESSION_PARAGON = 9
Global Const $GC_I_PROFESSION_DERVISH = 10
Global Const $GC_I_ATTRIBUTE_FAST_CASTING = 0
Global Const $GC_I_ATTRIBUTE_ILLUSION_MAGIC = 1
Global Const $GC_I_ATTRIBUTE_DOMINATION_MAGIC = 2
Global Const $GC_I_ATTRIBUTE_INSPIRATION_MAGIC = 3
Global Const $GC_I_ATTRIBUTE_BLOOD_MAGIC = 4
Global Const $GC_I_ATTRIBUTE_DEATH_MAGIC = 5
Global Const $GC_I_ATTRIBUTE_SOUL_REAPING = 6
Global Const $GC_I_ATTRIBUTE_CURSES = 7
Global Const $GC_I_ATTRIBUTE_AIR_MAGIC = 8
Global Const $GC_I_ATTRIBUTE_EARTH_MAGIC = 9
Global Const $GC_I_ATTRIBUTE_FIRE_MAGIC = 10
Global Const $GC_I_ATTRIBUTE_WATER_MAGIC = 11
Global Const $GC_I_ATTRIBUTE_ENERGY_STORAGE = 12
Global Const $GC_I_ATTRIBUTE_HEALING_PRAYERS = 13
Global Const $GC_I_ATTRIBUTE_SMITING_PRAYERS = 14
Global Const $GC_I_ATTRIBUTE_PROTECTION_PRAYERS = 15
Global Const $GC_I_ATTRIBUTE_DIVINE_FAVOR = 16
Global Const $GC_I_ATTRIBUTE_STRENGTH = 17
Global Const $GC_I_ATTRIBUTE_AXE_MASTERY = 18
Global Const $GC_I_ATTRIBUTE_HAMMER_MASTERY = 19
Global Const $GC_I_ATTRIBUTE_SWORDSMANSHIP = 20
Global Const $GC_I_ATTRIBUTE_TACTICS = 21
Global Const $GC_I_ATTRIBUTE_BEAST_MASTERY = 22
Global Const $GC_I_ATTRIBUTE_EXPERTISE = 23
Global Const $GC_I_ATTRIBUTE_WILDERNESS_SURVIVAL = 24
Global Const $GC_I_ATTRIBUTE_MARKSMANSHIP = 25
Global Const $GC_I_ATTRIBUTE_DAGGER_MASTERY = 29
Global Const $GC_I_ATTRIBUTE_DEADLY_ARTS = 30
Global Const $GC_I_ATTRIBUTE_SHADOW_ARTS = 31
Global Const $GC_I_ATTRIBUTE_COMMUNING = 32
Global Const $GC_I_ATTRIBUTE_RESTORATION_MAGIC = 33
Global Const $GC_I_ATTRIBUTE_CHANNELING_MAGIC = 34
Global Const $GC_I_ATTRIBUTE_CRITICAL_STRIKES = 35
Global Const $GC_I_ATTRIBUTE_SPAWNING_POWER = 36
Global Const $GC_I_ATTRIBUTE_SPEAR_MASTERY = 37
Global Const $GC_I_ATTRIBUTE_COMMAND = 38
Global Const $GC_I_ATTRIBUTE_MOTIVATION = 39
Global Const $GC_I_ATTRIBUTE_LEADERSHIP = 40
Global Const $GC_I_ATTRIBUTE_SCYTHE_MASTERY = 41
Global Const $GC_I_ATTRIBUTE_WIND_PRAYERS = 42
Global Const $GC_I_ATTRIBUTE_EARTH_PRAYERS = 43
Global Const $GC_I_ATTRIBUTE_MYSTICISM = 44
Global Const $GC_I_ATTRIBUTE_NONE = 0xFF
Global Const $GC_AI2_ALL_ATTRIBUTES_BY_PROFESSION[10][6] = [ _
    [$GC_I_PROFESSION_WARRIOR, $GC_I_ATTRIBUTE_STRENGTH, $GC_I_ATTRIBUTE_AXE_MASTERY, $GC_I_ATTRIBUTE_HAMMER_MASTERY, $GC_I_ATTRIBUTE_SWORDSMANSHIP, $GC_I_ATTRIBUTE_TACTICS], _
    [$GC_I_PROFESSION_RANGER, $GC_I_ATTRIBUTE_BEAST_MASTERY, $GC_I_ATTRIBUTE_EXPERTISE, $GC_I_ATTRIBUTE_WILDERNESS_SURVIVAL, $GC_I_ATTRIBUTE_MARKSMANSHIP], _
    [$GC_I_PROFESSION_MONK, $GC_I_ATTRIBUTE_HEALING_PRAYERS, $GC_I_ATTRIBUTE_SMITING_PRAYERS, $GC_I_ATTRIBUTE_PROTECTION_PRAYERS, $GC_I_ATTRIBUTE_DIVINE_FAVOR], _
    [$GC_I_PROFESSION_NECROMANCER, $GC_I_ATTRIBUTE_BLOOD_MAGIC, $GC_I_ATTRIBUTE_DEATH_MAGIC, $GC_I_ATTRIBUTE_SOUL_REAPING, $GC_I_ATTRIBUTE_CURSES], _
    [$GC_I_PROFESSION_MESMER, $GC_I_ATTRIBUTE_FAST_CASTING, $GC_I_ATTRIBUTE_ILLUSION_MAGIC, $GC_I_ATTRIBUTE_DOMINATION_MAGIC, $GC_I_ATTRIBUTE_INSPIRATION_MAGIC], _
    [$GC_I_PROFESSION_ELEMENTALIST, $GC_I_ATTRIBUTE_AIR_MAGIC, $GC_I_ATTRIBUTE_EARTH_MAGIC, $GC_I_ATTRIBUTE_FIRE_MAGIC, $GC_I_ATTRIBUTE_WATER_MAGIC, $GC_I_ATTRIBUTE_ENERGY_STORAGE], _
    [$GC_I_PROFESSION_ASSASSIN, $GC_I_ATTRIBUTE_CRITICAL_STRIKES, $GC_I_ATTRIBUTE_DAGGER_MASTERY, $GC_I_ATTRIBUTE_DEADLY_ARTS, $GC_I_ATTRIBUTE_SHADOW_ARTS], _
    [$GC_I_PROFESSION_RITUALIST, $GC_I_ATTRIBUTE_SPAWNING_POWER, $GC_I_ATTRIBUTE_COMMUNING, $GC_I_ATTRIBUTE_RESTORATION_MAGIC, $GC_I_ATTRIBUTE_CHANNELING_MAGIC], _
    [$GC_I_PROFESSION_PARAGON, $GC_I_ATTRIBUTE_SPEAR_MASTERY, $GC_I_ATTRIBUTE_COMMAND, $GC_I_ATTRIBUTE_MOTIVATION , $GC_I_ATTRIBUTE_LEADERSHIP], _
    [$GC_I_PROFESSION_DERVISH, $GC_I_ATTRIBUTE_SCYTHE_MASTERY, $GC_I_ATTRIBUTE_WIND_PRAYERS, $GC_I_ATTRIBUTE_EARTH_PRAYERS, $GC_I_ATTRIBUTE_MYSTICISM] _
]
Global Const $GC_AI2_PRRIMARY_ATTRIBUTES_BY_PROFESSION[10][2] = [ _
    [$GC_I_PROFESSION_WARRIOR, $GC_I_ATTRIBUTE_STRENGTH], _
    [$GC_I_PROFESSION_RANGER, $GC_I_ATTRIBUTE_EXPERTISE], _
    [$GC_I_PROFESSION_MONK, $GC_I_ATTRIBUTE_DIVINE_FAVOR], _
    [$GC_I_PROFESSION_NECROMANCER, $GC_I_ATTRIBUTE_SOUL_REAPING], _
    [$GC_I_PROFESSION_MESMER, $GC_I_ATTRIBUTE_FAST_CASTING], _
    [$GC_I_PROFESSION_ELEMENTALIST, $GC_I_ATTRIBUTE_ENERGY_STORAGE], _
    [$GC_I_PROFESSION_ASSASSIN, $GC_I_ATTRIBUTE_CRITICAL_STRIKES], _
    [$GC_I_PROFESSION_RITUALIST, $GC_I_ATTRIBUTE_SPAWNING_POWER], _
    [$GC_I_PROFESSION_PARAGON, $GC_I_ATTRIBUTE_LEADERSHIP], _
    [$GC_I_PROFESSION_DERVISH, $GC_I_ATTRIBUTE_MYSTICISM] _
]
Global Const $GC_AI2_SECONDARY_ATTRIBUTES_BY_PROFESSION[10][5] = [ _
	[$GC_I_PROFESSION_WARRIOR, $GC_I_ATTRIBUTE_AXE_MASTERY, $GC_I_ATTRIBUTE_HAMMER_MASTERY, $GC_I_ATTRIBUTE_SWORDSMANSHIP, $GC_I_ATTRIBUTE_TACTICS], _
	[$GC_I_PROFESSION_RANGER, $GC_I_ATTRIBUTE_BEAST_MASTERY, $GC_I_ATTRIBUTE_WILDERNESS_SURVIVAL, $GC_I_ATTRIBUTE_MARKSMANSHIP], _
	[$GC_I_PROFESSION_MONK, $GC_I_ATTRIBUTE_HEALING_PRAYERS, $GC_I_ATTRIBUTE_SMITING_PRAYERS, $GC_I_ATTRIBUTE_PROTECTION_PRAYERS], _
	[$GC_I_PROFESSION_NECROMANCER, $GC_I_ATTRIBUTE_BLOOD_MAGIC, $GC_I_ATTRIBUTE_DEATH_MAGIC, $GC_I_ATTRIBUTE_CURSES], _
	[$GC_I_PROFESSION_MESMER, $GC_I_ATTRIBUTE_ILLUSION_MAGIC, $GC_I_ATTRIBUTE_DOMINATION_MAGIC, $GC_I_ATTRIBUTE_INSPIRATION_MAGIC], _
	[$GC_I_PROFESSION_ELEMENTALIST, $GC_I_ATTRIBUTE_AIR_MAGIC, $GC_I_ATTRIBUTE_EARTH_MAGIC, $GC_I_ATTRIBUTE_FIRE_MAGIC, $GC_I_ATTRIBUTE_WATER_MAGIC], _
	[$GC_I_PROFESSION_ASSASSIN, $GC_I_ATTRIBUTE_DAGGER_MASTERY, $GC_I_ATTRIBUTE_DEADLY_ARTS, $GC_I_ATTRIBUTE_SHADOW_ARTS], _
	[$GC_I_PROFESSION_RITUALIST, $GC_I_ATTRIBUTE_COMMUNING, $GC_I_ATTRIBUTE_RESTORATION_MAGIC, $GC_I_ATTRIBUTE_CHANNELING_MAGIC], _
	[$GC_I_PROFESSION_PARAGON, $GC_I_ATTRIBUTE_SPEAR_MASTERY, $GC_I_ATTRIBUTE_COMMAND, $GC_I_ATTRIBUTE_MOTIVATION], _
	[$GC_I_PROFESSION_DERVISH, $GC_I_ATTRIBUTE_SCYTHE_MASTERY, $GC_I_ATTRIBUTE_WIND_PRAYERS, $GC_I_ATTRIBUTE_EARTH_PRAYERS] _
]
Global Const $GC_AS_ATTRIBUTE_NAMES[45] = [ _
    "Fast Casting", "Illusion Magic", "Domination Magic", "Inspiration Magic", _
    "Blood Magic", "Death Magic", "Soul Reaping", "Curses", _
    "Air Magic", "Earth Magic", "Fire Magic", "Water Magic", "Energy Storage", _
    "Healing Prayers", "Smiting Prayers", "Protection Prayers", "Divine Favor", _
    "Strength", "Axe Mastery", "Hammer Mastery", "Swordsmanship", "Tactics", _
    "Beast Mastery", "Expertise", "Wilderness Survival", "Marksmanship", _
    "Unknown", "Unknown", "Unknown", _
    "Dagger Mastery", "Deadly Arts", "Shadow Arts", _
    "Communing", "Restoration Magic", "Channeling Magic", _
    "Critical Strikes", "Spawning Power", _
    "Spear Mastery", "Command", "Motivation", "Leadership", _
    "Scythe Mastery", "Wind Prayers", "Earth Prayers", "Mysticism" _
]
Global Const $GC_I_ATTRIBUTE_RESULT_SUCCESS = 0
Global Const $GC_I_ATTRIBUTE_RESULT_INVALID_ID = 1
Global Const $GC_I_ATTRIBUTE_RESULT_INVALID_VALUE = 2
Global Const $GC_I_ATTRIBUTE_RESULT_NO_POINTS = 3
Global Const $GC_I_ATTRIBUTE_RESULT_MAX_REACHED = 4
#EndRegion Module Constants